module(name = "main", version="")

bazel_dep(name = "platforms", version = "1.0.0")
# -- bazel_dep definitions -- #

git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
# -- use_repo_rule statements -- #


git_repository(
  name = "com_google_googletest",
  remote = "https://github.com/google/googletest",
  tag = "v1.14.0",
)
# -- repo definitions -- #
